name: Update Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag version
        id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          release_name: Release ${{ steps.tag.outputs.version }}
          body: |
            # 사용 방법
            
            아래 실행 파일의 이름으로 설정된 확장자 파일을 다운로드, 적합한 구동 프로그램이 사전에 설치된 상태로 구동.
            
            ## HMI
            - 실행 파일 : default.xpd (신호등.xpd)
            - 구동 프로그램 : XP-Builder
            
            ## PLC
            - 실행 파일 : default.xgwx (신호등.xgwx)
            - 구동 프로그램 : XG-5000
          draft: false
          prerelease: false

      - name: Upload HMI XPD file
        run: |
          if [ -f "HMI/신호등.xpd" ]; then
            gh release upload ${{ steps.tag.outputs.version }} "HMI/신호등.xpd"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Upload PLC XGWX file
        run: |
          if [ -f "PLC/신호등.xgwx" ]; then
            gh release upload ${{ steps.tag.outputs.version }} "PLC/신호등.xgwx"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
